/* Autogenerated by script/mkversion.sh */
#define SAMBA_VERSION_MAJOR 3
#define SAMBA_VERSION_MINOR 3
#define SAMBA_VERSION_RELEASE 2
#define SAMBA_VERSION_OFFICIAL_STRING "3.3.2"
#define SAMBA_VERSION_STRING samba_version_string()
