/* Autogenerated by script/mkversion.sh */
#define SAMBA_VERSION_MAJOR 3
#define SAMBA_VERSION_MINOR 3
#define SAMBA_VERSION_RELEASE 0
#define SAMBA_VERSION_PRE_RELEASE 2
#define SAMBA_VERSION_OFFICIAL_STRING "3.3.0pre2"
#define SAMBA_VERSION_STRING samba_version_string()
