.TH ADDTOSMBPASS 8 12-Apr-1998
.SH NAME
addtosmbpass \- add new entries to smbpasswd files
.SH SYNOPSIS
addtosmbpass name1 [name2 ...] < smbpasswd.in > smbpasswd.out
.SH DESCRIPTION
.B addtosmbpass
adds a new account to an existing smbpasswd file. The existing
smbpasswd file is passed as standard input to the program. The new
smbpasswd file is dumped to standard output.
.SH FILES
.TP
/etc/samba/smbpasswd
Encrypted passwords file for the Samba daemons
.SH SEE ALSO
samba(7), nmbd(8), smbd(8)
.SH AUTHOR
Eloy A. Paris <peloy@debian.org> (man page based on sendmailconfig's man page
by Robert Leslie <rob@mars.org>)
