'\" t
.\"     Title: idmap_tdb
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/14/2011
.\"    Manual: System Administration tools
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "IDMAP_TDB" "8" "06/14/2011" "Samba 3\&.5" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
idmap_tdb \- Samba\'s idmap_tdb Backend for Winbind
.SH "DESCRIPTION"
.PP
The idmap_tdb plugin is the default backend used by winbindd for storing SID/uid/gid mapping tables\&.
.PP
In contrast to read only backends like idmap_rid, it is an allocating backend: This means that it needs to allocate new user and group IDs in order to create new mappings\&. The allocator can be provided by the idmap_tdb backend itself or by any other allocating backend like idmap_ldap or idmap_tdb2\&. This is configured with the parameter
\fIidmap alloc backend\fR\&.
.PP
Note that in order for this (or any other allocating) backend to function at all, the default backend needs to be writeable\&. The ranges used for uid and gid allocation are the default ranges configured by "idmap uid" and "idmap gid"\&.
.PP
Furthermore, since there is only one global allocating backend responsible for all domains using writeable idmap backends, any explicitly configured domain with idmap backend tdb should have the same range as the default range, since it needs to use the global uid / gid allocator\&. See the example below\&.
.SH "IDMAP OPTIONS"
.PP
range = low \- high
.RS 4
Defines the available matching uid and gid range for which the backend is authoritative\&. If the parameter is absent, Winbind fails over to use the "idmap uid" and "idmap gid" options from smb\&.conf\&.
.RE
.SH "EXAMPLES"
.PP
This example shows how tdb is used as a the default idmap backend\&. It configures the idmap range through the global options for all domains encountered\&. This same range is used for uid/gid allocation\&.
.sp
.if n \{\
.RS 4
.\}
.nf
	[global]
	# "idmap backend = tdb" is redundant here since it is the default
	idmap backend = tdb
	idmap uid = 1000000\-2000000
	idmap gid = 1000000\-2000000
	
.fi
.if n \{\
.RE
.\}
.PP
This (rather theoretical) example shows how tdb can be used as the allocating backend while ldap is the default backend used to store the mappings\&. It adds an explicit configuration for some domain DOM1, that uses the tdb idmap backend\&. Note that the same range as the default uid/gid range is used, since the allocator has to serve both the default backend and the explicitly configured domain DOM1\&.
.sp
.if n \{\
.RS 4
.\}
.nf
	[global]
	idmap backend = ldap
	idmap uid = 1000000\-2000000
	idmap gid = 1000000\-2000000
	# use a different uid/gid allocator:
	idmap alloc backend = tdb

	idmap config DOM1 : backend = tdb
	idmap config DOM1 : range = 1000000\-2000000
	
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&.
