#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
	update-alternatives --install /usr/bin/locktest locktest /usr/bin/locktest.samba3
	update-alternatives --install /usr/bin/nsstest nsstest /usr/bin/nsstest.samba3
	update-alternatives --install /usr/bin/masktest masktest /usr/bin/masktest.samba3
	update-alternatives --install /usr/bin/smbtorture smbtorture /usr/bin/smbtorture.samba3
fi

#DEBHELPER#

exit 0
