.\"     Title: ldbadd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 11/20/2008
.\"    Manual: User Commands
.\"    Source: Samba 3.2
.\"
.TH "LDBADD" "1" "11/20/2008" "Samba 3\.2" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ldbadd - Command-line utility for adding records to an LDB
.SH "SYNOPSIS"
.HP 1
ldbadd [\-h] [\-H\ LDB\-URL] [ldif\-file1] [ldif\-file2] [\.\.\.]
.SH "DESCRIPTION"
.PP
ldbadd adds records to an ldb(7) database\. It reads the ldif(5) files specified on the command line and adds the records from these files to the LDB database, which is specified by the \-H option or the LDB_URL environment variable\.
.PP
If \- is specified as a ldb file, the ldif input is read from standard input\.
.SH "OPTIONS"
.PP
\-h
.RS 4
Show list of available options\.
.RE
.PP
\-H <ldb\-url>
.RS 4
LDB URL to connect to\. See ldb(7) for details\.
.RE
.SH "ENVIRONMENT"
.PP
LDB_URL
.RS 4
LDB URL to connect to (can be overrided by using the \-H command\-line option\.)
.RE
.SH "VERSION"
.PP
This man page is correct for version 4\.0 of the Samba suite\.
.SH "SEE ALSO"
.PP
ldb(7), ldbmodify, ldbdel, ldif(5)
.SH "AUTHOR"
.PP
ldb was written by
Andrew Tridgell\.
.PP
If you wish to report a problem or make a suggestion then please see the
: http://ldb.samba.org/
web site for current contact and maintainer information\.
.PP
This manpage was written by Jelmer Vernooij\.
