#!/bin/sh -e
#
# $Id$
#

for patch in debian/patches/*.patch; do
	patch -p1 -R < $patch
done

perl -pi -e's/-.* for Debian//' source/include/version.h

# Regenerate configure only if it is older than configure.in
[ source/configure -ot source/configure.in ] && (cd source && autoconf)

exit 0
